version: "2"
services: 
  
    php:
      image: php:7
    mariadb:
      image: mariadb:latest
      container_name: wordpress-mariadb
      volumes:
       - ./db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "8081:3306"
    phpmyadmin: 
      image: phpmyadmin/phpmyadmin:latest
      container_name: wordpress-admin
      links: 
        - mariadb:mysql
      environment: 
        PMA_HOST: mariadb
      ports:
        - "8080:80"
    wordpress: 
      image: wordpress:latest
      volumes:
        - ./wordpress:/var/www/html
      container_name: wordpress-compose
      links: 
        - mariadb:mysql
      environment:
        WORDPRESS_DB_PASSWORD: root
      ports: 
        - "8082:80"